### ISSUE TITLE
Basic layout of Sign Up Screen

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#1]
You have to make the basic layout of sign up screen. 
Check below link for the design of sign up screen.
[Figma link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
As of now you don't have to worry about the styling or designing. Create just basic buttons and text fields. 

Please make sure to make a new dart file before start working.

**Comment by vipulranjansahu** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Darkknight131714** [comment]
claim

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by adtoria** [comment]
Claim

**Comment by Mantraraj8472** [comment]
I want to claim

**Comment by The-Divyansh** [comment]
claim

**Comment by NEHA15012002** [comment]
claim

**Comment by Sam-commit** [comment]
> claim

go for it, I have assigned it to you

**Comment by hardikarora2** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by Anushka1309** [comment]
claim

**Comment by vaibhavsahu342** [comment]
claim
