### ISSUE TITLE
Implement Bottom Navigation Bar

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#12]
Implement a Bottom Navigation Bar on the Home Screen. For reference you can check the design on provided figma link.
As of now you don't have to implement any functionality of bottom navigation bar, just make its basic structure.

**Comment by Monik09** [comment]
claim

**Comment by Tushargupta9800** [comment]
claim

**Comment by Palak-2109** [comment]
claim

**Comment by anirudhhhh** [comment]
I want to claim this issue
name: Anirudh Agrawal

**Comment by Sam-commit** [comment]
> claim

go for it

**Comment by underoot-iota** [comment]
claim
