### ISSUE TITLE
Improve UI of Login Screen

### ISSUE THREAD

**Issue by lalit-commits** [opencodeiiita/Ask-Us-Frontend#16]
Improve UI of Login Screen ,style it as in below figma link.
Check below link for the design of Login screen.
[Figma Link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
* Attach screen shot of output

**Comment by batflarrow** [comment]
claim

**Comment by shlesh** [comment]
claim

**Comment by vaibhavsahu342** [comment]
claim

**Comment by Hemant-appd** [comment]
claim

**Comment by shaliniagrawal2512** [comment]
claim
