### ISSUE TITLE
Add Continuos integration 

### ISSUE THREAD

**Issue by Monik09** [opencodeiiita/Ask-Us-Frontend#17]
Adding continuous integration using github actions to check if the app is correctly building or there is an issue in it so that no PR is merged before correcting the error.

This issue will help us remove issues during final build of the app.

If this issue is good to go, I will definitely like to work on it.

**Comment by Sam-commit** [comment]
yes ofcourse !! go for it

**Comment by Hemant-appd** [comment]
claim
