### ISSUE TITLE
Basic layout of Login Screen

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#2]
You have to make the basic layout of Login screen. 
Check below link for the design of Login  screen.
[Figma link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
As of now you don't have to worry about the styling or designing. Create just basic buttons and text fields. 

please make sure to make a new dart file before start working.

**Comment by sanjay395** [comment]
claim

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by Darkknight131714** [comment]
claim

**Comment by The-Divyansh** [comment]
claim

**Comment by NEHA15012002** [comment]
claim

**Comment by Mantraraj8472** [comment]
Claim

**Comment by Sam-commit** [comment]
> claim

go for it , i have assigned it to you

**Comment by naman-cr** [comment]
claim, i want to work on this

**Comment by Anushka1309** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by hotblooded058** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by Tushargupta9800** [comment]
claim
