### ISSUE TITLE
Styling app

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#20]
As of now, basic layout of the screens have been created. Now make a new dart file with the name constants.dart and add Styling of buttons and text field as constants so they can be applied to all screens with little modification. (You don't have to apply changes to screens as a part of this issue, just make constants.dart file ).

**Comment by Tushargupta9800** [comment]
claim

**Comment by Sam-commit** [comment]
go for it !!
