### ISSUE TITLE
Openning new issues

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#27]
If you want to open or work on a new issue you find in the app. Comment here , and if suitable, we will open that as an separate issue.

**Comment by Monik09** [comment]
I want to update the readme by adding:
- Add github actions successful/unsuccessful tag in readme
- Adding tips to follow so that your code is a successful build in how to contribute section.
I want to work on this.

**Comment by Monik09** [comment]
@Sam-commit I observed there are UI mismatches with the Figma design like some of them are: 
![image](https://user-images.githubusercontent.com/52850691/136273416-235d2022-3666-490b-914a-cdcf72e6bd96.png)
- In this upper two borders should not be rounded and some more UI issues with text positions
- In conformity in the header textformfields of HomePage and Answer Page.

In this issue, all these issues will be solved. I would like to solve these issues
