### ISSUE TITLE
Fixing continuous integration

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#28]
Fix the flutter-ci.yml file updated in pr #25 as it is not working properly.

**Comment by jalanprakhar** [comment]
claim

**Comment by Monik09** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by jalanprakhar** [comment]
@Sam-commit i claimed the issue before him!

**Comment by Monik09** [comment]
> > @Sam-commit Can I know what is required actually? The files are not actually formatted correctly that's why the main branch's action is showing error.
> 
> yes I agree with you and since everyone is making commits, its not possible to stay with the correct format as of now. I tried removing that step but that also is not working. So either correct it in some way so that it can ignore formatting or you can remove it and we can implement it later after refactoring the whole code once the basic layout is done.

Oh ok I completely understand what you are saying.

**Comment by Monik09** [comment]
These lines are important as if I remove the analyzing line there are high chances the build will fail too if there are errors. So currently I think I should comment out the file and we can start ci again after getting some stable code.
