### ISSUE TITLE
Create Basic Layout of Profile  Page

### ISSUE THREAD

**Issue by lalit-commits** [opencodeiiita/Ask-Us-Frontend#3]
You have to make the basic layout of Profile Page screen. 
Check below link for the design of Profile Page screen.
[Figma link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
Upload dummy data(image and profile info) and kindly ignore bottom Navbar as of now.
* Please make sure to code in a new dart file.

**Comment by vipulranjansahu** [comment]
claim

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by Darkknight131714** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by Monik09** [comment]
claim

**Comment by Anushka1309** [comment]
claim

**Comment by hotblooded058** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by Tushargupta9800** [comment]
claim

**Comment by janhaviiii** [comment]
claim

**Comment by vaibhavsahu342** [comment]
claim
