### ISSUE TITLE
Basic layout of Home Screen 

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#4]
You have to make the basic layout of Home screen. 
Check below link for the design of Home screen.
[Figma link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
This is the screen where all the posts from different people will be visible, so make it scrollable (hint:- make a new class for the posts).

Make a new dart file and and populate it with dummy data. As of now do not care about styling just implement basic layout. Ignore bottom navigation bar.

**Comment by Darkknight131714** [comment]
claim

**Comment by Monik09** [comment]
claim

**Comment by Sam-commit** [comment]
> claim

go for it, i have assigned you the issue

**Comment by hardikarora2** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by Kunal-8789** [comment]
claim
