### ISSUE TITLE
Create basic layout of Answer Screen

### ISSUE THREAD

**Issue by lalit-commits** [opencodeiiita/Ask-Us-Frontend#5]
You have to make the basic layout of Answer screen. 
Check below link for the design of Answer screen.
[Figma link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=12%3A211)
Don't worry about styling as of now just implement basic layout with dummy data.(Implement scrollable view for answer)

* Kindly code in a new dart file
* Ignore bottom navbar as of now

**Comment by Monik09** [comment]
claim

**Comment by The-Divyansh** [comment]
claim

**Comment by Kunal-8789** [comment]
Claim

**Comment by adtoria** [comment]
Claim

**Comment by hotblooded058** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by nitheesh96** [comment]
claim

**Comment by Tushargupta9800** [comment]
claim
