### ISSUE TITLE
Design App Icon 

### ISSUE THREAD

**Issue by lalit-commits** [opencodeiiita/Ask-Us-Frontend#52]
Design App Icon for Ask Us app.
Add screenshot and drive link of high quality icon in comments below. Whose icon will be selected, he will get the points.

The Last date for this issue is 25 October.

NO NEED TO CLAIM THIS ISSUE.

**Comment by AKI35429** [comment]
ISSUE: 52
![APP ICON](https://user-images.githubusercontent.com/76589891/137379130-c65b3b6b-d27b-4833-9b00-16ef41aa871e.png)

https://drive.google.com/file/d/1koOAow6PHivbYYlBmCvGYnwfyHnIeaxk/view?usp=sharing

**Comment by Sam-commit** [comment]
> Issue: 52
> 
> ![Ask Us](https://user-images.githubusercontent.com/91134684/137271888-36c0cbfe-bd1e-4ae3-99b8-3a50e1545430.png)
> 
> https://drive.google.com/file/d/10UN4odMsfLXTTHVSwObR8V_htcpynyas/view?usp=sharing

Thanks for trying but I think it is not going with the theme of the app much. You can improve it and comment again

**Comment by lalit-commits** [comment]
> issue: 52 ![Askus](https://user-images.githubusercontent.com/91134684/137516029-713ccd85-f808-4a28-8b11-20e3573ed77a.png)
> 
> @Sam-commit review this one also

Great Work 🔥

**Comment by lalit-commits** [comment]
> issue:52
> 
> ![ASk_US FRONTEDask_us_front svg](https://user-images.githubusercontent.com/88645562/138574125-821ee985-73ee-4210-93cc-f9cdb4d068f5.png)



> ![Ask us](https://user-images.githubusercontent.com/76650941/138747703-3fb3874b-d76a-4eed-bfa5-58620abdf88b.png)
> 
> The drive link : https://drive.google.com/drive/folders/1gHCQ692zDa6pl8_ACzJ_54i6LaqW56pu?usp=sharing



> issue:52
> 
> ![ASk_US FRONTEDask_us_front svg](https://user-images.githubusercontent.com/88645562/138574125-821ee985-73ee-4210-93cc-f9cdb4d068f5.png)

@kaneki-ken260  @hotblooded058  @shreya-0508  congratulations the icons designed by you have been selected. Kindly send PR with drive link of icon designed by you so we can give you points.
