### ISSUE TITLE
Image picker on profile screen is not working

### ISSUE THREAD

**Issue by lalit-commits** [opencodeiiita/Ask-Us-Frontend#59]
Find Bug in image picker and also increase size of circular avtar to make profile screen UI similar to given [Figma Link](https://www.figma.com/file/DrJfbkx9c5h2ac4dQtfgWn/AskUs?node-id=0%3A1)

**Comment by AgrimVerma** [comment]
Claim

**Comment by Sam-commit** [comment]
this issue is open now

**Comment by KIRTEE-TECH** [comment]
im almost done with the task , i will make my PR before 12.
