### ISSUE TITLE
Fetching all the questions and showing them on question screen

### ISSUE THREAD

**Issue by Sam-commit** [opencodeiiita/Ask-Us-Frontend#64]
Write a function to fetch the list of questions and show the unanswered questions on the question screen. Refer to the readme for api end points and schema.
For now the user data (by whom the question is posted) is not available so use dummy data.

**Comment by Sam-commit** [comment]
@shlesh any updates?

**Comment by shlesh** [comment]
sir i'll make the PR by morning

**Comment by Sam-commit** [comment]
> sir i'll make the PR by morning @Sam-commit

any update?
